<<<<<<< HEAD
[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
=======
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
>>>>>>> 1d95ab3 (Update SocialMedias and portfolio)
